# Generated by Django 4.0.3 on 2022-03-14 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('rare', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'редкость',
                'verbose_name_plural': 'редкость',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Ценна')),
                ('hero', models.CharField(max_length=155, verbose_name='Герой')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('rare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_rare', to='dota.rare', verbose_name='редкость')),
            ],
            options={
                'verbose_name': 'скин',
                'verbose_name_plural': 'скины',
            },
        ),
    ]
